# Native portable build: no broker/cache processes or compiler runtime DLLs.
include(FetchContent)
enable_language(RC)
if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()
if(MINGW)
  # Use portable source paths in diagnostics, including dependency assertions.
  get_filename_component(portable_source_root "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
  get_filename_component(portable_compiler_bin "${CMAKE_CXX_COMPILER}" DIRECTORY)
  get_filename_component(portable_compiler_root "${portable_compiler_bin}/.." ABSOLUTE)
  set(portable_path_maps
    "${portable_source_root}=/src"
    "${CMAKE_CURRENT_BINARY_DIR}=/build"
    "${portable_compiler_root}=/toolchain")
  if(FETCHCONTENT_SOURCE_DIR_BOOST_HEADERS)
    list(APPEND portable_path_maps "${FETCHCONTENT_SOURCE_DIR_BOOST_HEADERS}=/vendor/boost")
  endif()
  foreach(path_map IN LISTS portable_path_maps)
    add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-ffile-prefix-map=${path_map}>")
  endforeach()
endif()
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(protobuf_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(protobuf_WITH_ZLIB OFF CACHE BOOL "" FORCE)
set(ZLIB_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_OPENSSL_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_ZLIB_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
set(HTTPLIB_USE_BROTLI_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
FetchContent_Declare(protobuf URL https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.12.tar.gz)
FetchContent_Declare(boost_headers URL https://archives.boost.io/release/1.85.0/source/boost_1_85_0.tar.gz URL_HASH SHA256=be0d91732d5b0cc6fbb275c7939974457e79b54d6f07ce2e3dfdd68bef883b0b SOURCE_SUBDIR headers-only)
FetchContent_Declare(nlohmann_json URL https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz)
FetchContent_Declare(httplib URL https://github.com/yhirose/cpp-httplib/archive/refs/tags/v0.15.3.tar.gz)
FetchContent_Declare(zlib URL https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz)
FetchContent_Declare(sqlite_source URL https://www.sqlite.org/2024/sqlite-amalgamation-3450100.zip)
FetchContent_MakeAvailable(protobuf nlohmann_json httplib zlib)
FetchContent_MakeAvailable(boost_headers sqlite_source)
add_library(portable_sqlite STATIC ${sqlite_source_SOURCE_DIR}/sqlite3.c)
target_include_directories(portable_sqlite PUBLIC ${sqlite_source_SOURCE_DIR})
target_compile_definitions(portable_sqlite PRIVATE SQLITE_THREADSAFE=1)
add_library(portable_dependencies INTERFACE)
target_include_directories(portable_dependencies INTERFACE ${boost_headers_SOURCE_DIR} ${zlib_SOURCE_DIR} ${zlib_BINARY_DIR})
target_compile_definitions(portable_dependencies INTERFACE PIPELINE_PORTABLE BOOST_ERROR_CODE_HEADER_ONLY NOMINMAX _WIN32_WINNT=0x0A00)
target_link_libraries(portable_dependencies INTERFACE nlohmann_json::nlohmann_json httplib::httplib portable_sqlite zlibstatic bcrypt ws2_32 mswsock)
if(MINGW)
  # Recent MinGW injects a default manifest. Use our UTF-8 manifest instead,
  # without changing the compiler installation or merging two resource IDs.
  execute_process(COMMAND ${CMAKE_CXX_COMPILER} -dumpspecs OUTPUT_VARIABLE portable_specs COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE "%{!shared:%:if-exists(default-manifest.o%s)}" "" portable_specs "${portable_specs}")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/portable-gcc.specs" "${portable_specs}")
  add_link_options(-static -static-libgcc -static-libstdc++ -s "-specs=${CMAKE_CURRENT_BINARY_DIR}/portable-gcc.specs")
endif()
